import React from "react";
import CVupload from "../public/cvupload.svg";
import Practice from "../public/practice.svg";
import Feedback from "../public/feedback.svg";
import { MdOutlineFileUpload } from "react-icons/md";
import { FaMicrophoneAlt } from "react-icons/fa";
import IconCard from "./IconCard";
import { AiFillMessage } from "react-icons/ai";
const HowItWorks = () => {
  return (
    <div className=" flex flex-col gap-6 items-center">
      <h1 className="shadow-sm shadow-[#b6b6b6] border-[#1f1f1f] px-4 py-2 border-2 rounded-4xl">
        How it works
      </h1>
      <h1 className="text-3xl lg:text-5xl text-center">
        Smarter career preparation powered <br className="max-lg:hidden" /> by
        AI, designed for success.
      </h1>
      <p className="text-base lg:text-lg max-w-lg text-center text-subheadline">
        From uploading your resume to mastering interviews,{" "}
        <br className="max-lg:hidden" /> every step is seamless and purposeful.
      </p>
      <div className="grid grid-cols-2 gap-10 mt-20 place-items-center">
        <div className="flex flex-col h-full  ">
          <IconCard
            icon={<MdOutlineFileUpload size={40} />}
            title="Upload Your Resume"
            description={
              <>
                <span className="text-2xl">
                  {" "}
                  Start by uploading your CV. Our system scans and prepares it
                  for personalized analysis.
                </span>

                <ul className="mt-4 list-disc list-inside text-xl  space-y-1">
                  <li>Instant parsing of your experience</li>
                  <li>Matches skills to job descriptions</li>
                  <li>Highlights missing keywords</li>
                </ul>
              </>
            }
          />
          {/* <IconCard
            icon={<FaMicrophoneAlt size={40} />}
            title="Prepare for Interviews"
            description="Access dynamic, role-specific practice questions generated by AI. Practice by difficulty, improve timing, and boost your confidence."
          />
          <IconCard
            icon={<AiFillMessage size={40} />}
            title="Get Feedback & Track Progress"
            description="Receive instant feedback after each session. See performance scores, discover improvement areas, and stay on track."
            hide={true}
          /> */}
        </div>
        {/* large screen */}
        <div className=" border-4 border-[#0f0f0f] mask-radial-at-bottom-right  mask-b-from-60% bg-gradient-to-t from-transparent to-[#040303] max-w-xl h-[500px] rounded-lg p-6 overflow-hidden">
          <img
            src={CVupload.src}
            alt="cv-upload"
            className=" translate-y-20 translate-x-14   scale-120   "
          />
          {/* <img
            src={Practice.src}
            alt="cv-upload"
            className=" drop-shadow-xl drop-shadow-[#05362e]   object-cover w-[1000px]  border border-[#3b3b3b] rounded-lg"
          />
          <img
            src={Feedback.src}
            alt="cv-upload"
            className=" drop-shadow-xl drop-shadow-[#05362e]   object-cover w-[1000px] border border-[#3b3b3b] mb-20  rounded-lg"
          /> */}
        </div>
        {/* small screen */}
        {/* <div className="flex  xl:hidden overflow-scroll hide-scrollbar gap-20">
          <img
            src={CVupload.src}
            alt="cv-upload"
            className=" drop-shadow-xl drop-shadow-[#05362e] max-w-lg  object-contain h-full w-full border border-[#3b3b3b]  rounded-lg"
          />
          <img
            src={Practice.src}
            alt="cv-upload"
            className=" drop-shadow-xl drop-shadow-[#05362e] max-w-lg  object-contain h-full w-full  border border-[#3b3b3b] rounded-lg"
          />
          <img
            src={Feedback.src}
            alt="cv-upload"
            className=" drop-shadow-xl drop-shadow-[#05362e] max-w-lg  object-contain h-full w-full border border-[#3b3b3b] mb-20  rounded-lg"
          />
        </div> */}
      </div>
    </div>
  );
};

export default HowItWorks;
